const KEY='schooltrack_v2';
const defaultData={items:[],reports:[],history:[],settings:{dark:false,sound:true,lowThreshold:5}};
let data=load();
const $=id=>document.getElementById(id);
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}'),settings:{...defaultData.settings,...(JSON.parse(localStorage.getItem(KEY)||'{}').settings||{})}}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function statusFor(item){const q=Math.max(0,Number(item.quantity)||0);if(q===0)return ['out','Out of Stock'];if(q<=Number(data.settings.lowThreshold))return ['low','Low Stock'];return ['in','In Stock']}
function speak(msg){if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(msg);u.rate=.95;speechSynthesis.speak(u)}}
function clickSound(){if(!data.settings.sound)return;const a=$('clickSound');if(!a)return;a.currentTime=0;a.play().catch(()=>{});}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function addHistory(action,item,extra=''){data.history.unshift({date:new Date().toLocaleString(),action,item:item?.name||item?.id||'',extra})}
function nav(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));if(page==='add')resetForm();window.scrollTo({top:0,behavior:'smooth'});}
function resetForm(){ $('itemForm').reset();$('editIndex').value='';$('formTitle').textContent='Add Item';$('quantity').value=1; }
function render(){
 const items=data.items; const total=items.reduce((s,i)=>s+(+i.quantity||0),0);const borrowed=items.reduce((s,i)=>s+(+i.borrowed||0),0);const repair=items.reduce((s,i)=>s+(+i.repair||0),0);const missing=items.reduce((s,i)=>s+(+i.missing||0),0);let inc=0,low=0,out=0;items.forEach(i=>{const [st]=statusFor(i);if(st==='in')inc++;else if(st==='low')low++;else out++});$('totalCount').textContent=total;$('inCount').textContent=inc;$('lowCount').textContent=low;$('outCount').textContent=out;$('borrowedCount').textContent=borrowed;$('repairCount').textContent=repair;$('missingCount').textContent=missing;
 $('stockMessage').textContent=out?`${out} item${out>1?'s are':' is'} out of stock and ${low} ${low===1?'item is':'items are'} low stock.`:'Your inventory is up to date.';
 renderAlerts();renderInventory();renderReports();renderHistory();
 document.body.classList.toggle('dark',!!data.settings.dark);$('themeBtn').textContent=data.settings.dark?'☀️':'🌙';$('soundBtn').textContent=data.settings.sound?'🔊':'🔇';
}
function renderAlerts(){const alerts=data.items.filter(i=>['low','out'].includes(statusFor(i)[0]));$('alerts').innerHTML=alerts.length?alerts.slice(0,8).map(i=>{const [st,label]=statusFor(i);return `<div class="item-card"><div class="item-top"><div><div class="item-title">${esc(i.name)}</div><div class="meta">${esc(i.id)} · Qty ${+i.quantity||0}</div></div><span class="badge ${st==='out'?'bad':'warn'}">${label}</span></div></div>`}).join(''):'<div class="empty">✨ No low-stock or out-of-stock alerts.</div>'}
function renderInventory(){const q=($('search').value||'').toLowerCase();const f=$('filter').value;const arr=data.items.filter(i=>{const [st]=statusFor(i);const text=[i.id,i.name,i.category,i.location,i.condition].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(f==='borrowed'&&!(+i.borrowed>0))return false;if(f==='repair'&&!(+i.repair>0))return false;if(f==='missing'&&!(+i.missing>0))return false;if(['in','low','out'].includes(f)&&st!==f)return false;return true});$('inventoryList').innerHTML=arr.length?arr.map(i=>card(i)).join(''):'<div class="empty panel">No inventory items found.</div>'}
function card(i){const [st,label]=statusFor(i);const available=Math.max(0,(+i.quantity||0)-(+i.borrowed||0)-(+i.repair||0)-(+i.missing||0));return `<article class="item-card"><div class="item-top"><div><div class="item-title">${esc(i.name)}</div><div class="meta">${esc(i.id)} · ${esc(i.category||'Uncategorized')} · ${esc(i.location||'No location')}</div></div><span class="badge ${st==='out'?'bad':st==='low'?'warn':'good'}">${label}</span></div><div class="qty">${+i.quantity||0} <span class="meta">total</span></div><div class="meta">Available: ${available} · Borrowed: ${+i.borrowed||0} · Repair: ${+i.repair||0} · Missing: ${+i.missing||0}</div><div class="meta">Condition: ${esc(i.condition||'Good')} · Responsible: ${esc(i.responsible||'—')}</div><div class="item-actions"><button data-act="borrow" data-id="${esc(i.id)}">Borrow</button><button data-act="return" data-id="${esc(i.id)}">Return</button><button data-act="repair" data-id="${esc(i.id)}">Repair</button><button data-act="complete" data-id="${esc(i.id)}">Complete Repair</button><button data-act="missing" data-id="${esc(i.id)}">Missing</button><button data-act="found" data-id="${esc(i.id)}">Found</button><button data-act="edit" data-id="${esc(i.id)}">Edit</button><button data-act="delete" data-id="${esc(i.id)}">Delete</button></div></article>`}
function renderReports(){$('reportList').innerHTML=data.reports.length?data.reports.map((r,n)=>`<article class="item-card"><div class="item-top"><div><div class="item-title">${esc(r.problem)}</div><div class="meta">${esc(r.itemId)} · ${esc(r.reportedBy||'Anonymous')} · ${esc(r.date)}</div></div><span class="badge">${esc(r.status)}</span></div><div class="meta" style="margin-top:10px">Action: ${esc(r.action||'—')}</div><div class="item-actions"><button data-report="review" data-index="${n}">Under Review</button><button data-report="resolve" data-index="${n}">Resolved</button><button data-report="delete" data-index="${n}">Delete</button></div></article>`).join(''):'<div class="empty panel">No problem reports yet.</div>'}
function renderHistory(){$('historyList').innerHTML=data.history.length?data.history.slice(0,100).map(h=>`<article class="item-card"><div class="item-title">${esc(h.action)}</div><div class="meta">${esc(h.item)} · ${esc(h.date)}</div>${h.extra?`<div class="meta">${esc(h.extra)}</div>`:''}</article>`).join(''):'<div class="empty panel">No transactions yet.</div>'}
function find(id){return data.items.find(i=>i.id===id)}
function act(id,action){const i=find(id);if(!i)return;const available=Math.max(0,(+i.quantity||0)-(+i.borrowed||0)-(+i.repair||0)-(+i.missing||0));if(action==='borrow'){if(available<=0){toast('Cannot borrow: item is out of stock.');speak(`${i.name} is out of stock.`);return}i.borrowed=(+i.borrowed||0)+1;addHistory('Borrowed',i);toast('Item borrowed.');}if(action==='return'){if((+i.borrowed||0)<=0){toast('No borrowed units to return.');return}i.borrowed--;addHistory('Returned',i);toast('Item returned.')}if(action==='repair'){if(available<=0){toast('No available unit to send to repair.');return}i.repair=(+i.repair||0)+1;addHistory('Sent to Repair',i);toast('Sent to repair.')}if(action==='complete'){if((+i.repair||0)<=0){toast('No repair record.');return}i.repair--;addHistory('Repair Completed',i);toast('Repair completed.')}if(action==='missing'){if(available<=0){toast('No available unit to mark missing.');return}i.missing=(+i.missing||0)+1;addHistory('Marked Missing',i);toast('Marked missing.')}if(action==='found'){if((+i.missing||0)<=0){toast('No missing unit to mark found.');return}i.missing--;addHistory('Marked Found',i);toast('Marked found.')}save();announceStock(i)}
function announceStock(i){const [st,label]=statusFor(i);speak(`${i.name}: ${label}. Quantity ${+i.quantity||0}.`)}
$('itemForm').addEventListener('submit',e=>{e.preventDefault();const idx=$('editIndex').value;const obj={id:$('itemId').value.trim(),name:$('itemName').value.trim(),category:$('category').value.trim(),quantity:Math.max(0,+$('quantity').value||0),condition:$('condition').value,location:$('location').value.trim(),responsible:$('responsible').value.trim(),remarks:$('remarks').value.trim()};if(!obj.id||!obj.name){toast('Please enter Item ID and Item Name.');return}if(idx!==''){const old=data.items[+idx];obj.borrowed=old.borrowed||0;obj.repair=old.repair||0;obj.missing=old.missing||0;data.items[+idx]=obj;addHistory('Edited Item',obj)}else{if(data.items.some(i=>i.id.toLowerCase()===obj.id.toLowerCase())){toast('That Item ID already exists.');return}obj.borrowed=0;obj.repair=0;obj.missing=0;data.items.unshift(obj);addHistory('Added Item',obj)}save();toast('Item saved.');announceStock(obj);nav('inventory')});
$('inventoryList').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id, a=b.dataset.act;clickSound();if(a==='edit'){const i=find(id),idx=data.items.indexOf(i);$('editIndex').value=idx;$('formTitle').textContent='Edit Item';$('itemId').value=i.id;$('itemName').value=i.name;$('category').value=i.category||'';$('quantity').value=i.quantity||0;$('condition').value=i.condition||'Good';$('location').value=i.location||'';$('responsible').value=i.responsible||'';$('remarks').value=i.remarks||'';nav('add');return}if(a==='delete'){if(confirm('Delete this item?')){const i=find(id);data.items=data.items.filter(x=>x.id!==id);addHistory('Deleted Item',i);save();toast('Item deleted.')}return}act(id,a)});
$('search').addEventListener('input',renderInventory);$('filter').addEventListener('change',renderInventory);$('cancelEdit').addEventListener('click',()=>nav('inventory'));
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{clickSound();nav(b.dataset.nav)}));
$('themeBtn').addEventListener('click',()=>{clickSound();data.settings.dark=!data.settings.dark;save();toast(data.settings.dark?'Dark mode enabled.':'Light mode enabled.')});$('soundBtn').addEventListener('click',()=>{data.settings.sound=!data.settings.sound;save();if(data.settings.sound)clickSound();toast(data.settings.sound?'Sounds enabled.':'Sounds disabled.')});
$('newReportBtn').addEventListener('click',()=>{clickSound();const itemId=prompt('Item ID:');if(!itemId)return;const problem=prompt('What is the problem?');if(!problem)return;const reportedBy=prompt('Reported by:')||'';data.reports.unshift({itemId,problem,reportedBy,date:new Date().toLocaleString(),status:'Pending',action:''});addHistory('Problem Reported',find(itemId)||{name:itemId},problem);save();toast('Report added.')});
$('reportList').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;clickSound();const i=+b.dataset.index;if(b.dataset.report==='delete'){data.reports.splice(i,1)}else if(b.dataset.report==='review'){data.reports[i].status='Under Review'}else if(b.dataset.report==='resolve'){data.reports[i].status='Resolved';data.reports[i].action=prompt('Action taken:')||data.reports[i].action}save()});
$('backupBtn').addEventListener('click',()=>{clickSound();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='schooltrack-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded.')});
$('restoreFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x.items||!Array.isArray(x.items))throw new Error();data={...defaultData,...x,settings:{...defaultData.settings,...(x.settings||{})}};save();toast('Backup restored.')}catch{toast('Invalid backup file.')}});
$('csvBtn').addEventListener('click',()=>{clickSound();const rows=[['ID','Name','Category','Quantity','Borrowed','Repair','Missing','Condition','Location','Responsible','Remarks'],...data.items.map(i=>[i.id,i.name,i.category,i.quantity,i.borrowed||0,i.repair||0,i.missing||0,i.condition,i.location,i.responsible,i.remarks])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='schooltrack-inventory.csv';a.click();toast('CSV exported.')});
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
render();
